name: Update Airports Data

on:
  schedule:
    - cron: '0 0 1 * *' # Run at 00:00 on day-of-month 1.
  workflow_dispatch:

jobs:
  download-airports:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download airports.csv
        run: |
          curl -L -o current/airports.csv https://davidmegginson.github.io/ourairports-data/airports.csv

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add current/airports.csv
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to airports.csv"
          else
            git commit -m "Update airports.csv "
            git push
          fi
